export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
  params: { session, ...params },
}: {
  children: React.ReactNode;
  params: { session: any };
}) {
  return (
    <html lang="en">
      <body>
        <h1>Este titulo</h1>
        {children}
      </body>
    </html>
  );
}
